language: go
go: 1.8
install:
  - make setup
script:
  - make test
  - test -n "$TRAVIS_TAG" || go run main.go
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - test -n "$TRAVIS_TAG" && go run main.go
notifications:
  email: false
