
[[dependencies]]
  branch = "master"
  name = "github.com/gizak/termui"

[[dependencies]]
  branch = "master"
  name = "github.com/google/go-github"

[[dependencies]]
  branch = "master"
  name = "golang.org/x/oauth2"
